version: "3.7"
services:
  db: 
    image: postgres:17.0
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev

  redis:
    image: redis:latest
    container_name: redis_app
    command: --port 5300

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app 
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on: 
      - db
      - redis


  celery:
    build: 
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ['celery --app=tasks.tasks:celery worker -l INFO']
    depends_on:       
      - redis

  flower:
    build: 
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ['celery --app=tasks.tasks:celery flower']
    depends_on:
      - redis       
      - celery
    ports:
      - 5555:5555
